#Path: /Documents/MiguelVasquez/Python

print("[!] --------- Menu ----------- ")
print("[!] 1.CREAR GRUPO ARTEMIS:\n[!] 1.1 LISTAR CAMPERS DE ARTEMIS\n[!] 1.2 AGREGAR CAMPERS A ARTEMIS\n[!] 1.3 ELIMINAR CAMPERS DE ARTEMIS\n[!] 1.4 ORDENAR ALFABETICAMENTE EN LISTA DE ARTEMIS\n[!] 1.5 BUSCAR CAMPER EN LISTA DE ARTEMISCREAR GRUPO SPUTNIK\n[!] 2.2.1LISTAR CAMPERS DE SPUTNIK:\n[!] 2.2 AGREGAR CAMPERS A SPUTNIK\n[!] 2.3 ELIMINAR CAMPERS DE SPUTNIK\n[!] 2.4 ORDENAR ALFABETICAMENTE EN LISTA DE SPUTNIK\n[!] 2.5 BUSCAR CAMPER EN LISTA DE SPUTNIK")
int(input('\n[>] Digite su opcion: '))
